services:
  - type: web
    name: voice-translator
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y $(cat packages.txt)
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -c "from run_app import run; run()"
    envVars:
      - key: OPENAI_API_KEY
        sync: false # This means it needs to be set manually in Render dashboard
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free 